services:
  # This service builds and runs your Node.js backend from its Dockerfile
  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env
    # This helps with any potential DNS issues inside the container
    dns:
      - 8.8.8.8

  # This service runs Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # This ensures your backend is running before Prometheus starts
    depends_on:
      - backend

  # This service runs Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

