services:
  # ✅ NEW: This service builds and runs your Node.js backend
  backend:
    build: ./Backend  # Tells Docker to build the image from the Backend/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080" # Exposes your API to the outside world
    env_file:
      - ./Backend/.env # Loads your secrets from the .env file

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - backend # Ensures the backend starts before Prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
