global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "devpulse-backend"
    static_configs:
      # ✅ FIX: Use the service name 'backend' from docker-compose
      - targets: ["backend:8080"]
