global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "devpulse-backend"
    static_configs:
      # ✅ FIX: This special address tells the Prometheus container to connect
      # to the Node.js server running on your actual computer (the "host").
      - targets: ["host.docker.internal:8080"]